### ISSUE TITLE
Does the gt hand pose label is right?

### ISSUE THREAD

**Issue by AaronFengZY** [IRVLUTD/HO-Cap#11]
![output_sample_0](https://github.com/user-attachments/assets/efbf2781-a812-4ad2-bd93-86d23e574fd5)
![Uploading Weixin Screenshot_20241022120917.png…]()

When I use mano with gt pose and beta and global orientation to generate the verts and save it into a .obj file and visulize it, but it is obviously different

**Comment by AaronFengZY** [comment]
and the verts fig is here 
![Weixin Screenshot_20241024204636](https://github.com/user-attachments/assets/e8272739-aa3e-461a-9a94-df8bbdf18fe0)

**Comment by JWRoboticsVision** [comment]
Our dataset and codes are updated recently, and the issue should be fixed.
